name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 2.0.26
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: ">=2.6.0 <3.0.0"

#dependencies:

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.7.0
  build_web_compilers: ^2.3.0
