name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 3.1.0
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  test: ^1.16.0
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
