name: timeago_flutter
description: Timeago Widget for Flutter to create fuzzy timestamps. (e.g. "15 minutes ago").
version: 3.6.0
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  timeago: ^3.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
