name: timeago_flutter
description: Timeago Widget for Flutter to create fuzzy timestamps. (e.g. "15 minutes ago").
version: 0.3.0
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  timeago: ">=2.0.27 <3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
