name: timeago_flutter
description: Timeago Widget for Flutter to create fuzzy timestamps. (e.g. "15 minutes ago").
version: 1.0.0
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  timeago: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
